name: Deploy Azure Function

on:
  push:
    branches:
      - main   # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        working-directory: ./api
        run: npm install

      # 4️⃣ Ejecutar tests (opcional)
      - name: Run tests
        working-directory: ./api
        run: npm test || echo "No tests found"

      # 5️⃣ Iniciar sesión en Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Desplegar la Azure Function
      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: crudSilabo    # Nombre de tu Azure Function App
          package: ./API                    # Carpeta donde está el código
