name: Deploy Azure Function with RBAC

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'crudSilabo'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Descargar el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: npm install

      # 4️⃣ Ejecutar tests (opcional)
      - name: Run tests
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: npm test || echo "No tests found"

      # 5️⃣ Login a Azure usando Service Principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Desplegar usando Azure Functions Action con RBAC
      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          # No uses publish-profile aquí, ya que usamos RBAC

      # 7️⃣ Logout de Azure (buena práctica de seguridad)
      - name: Logout from Azure
        run: az logout
        if: always()