name: Deploy Azure Function

on:
  push:
    branches:
      - main   # Cambia si usas otra rama

env:
  AZURE_FUNCTIONAPP_NAME: 'crudSilabo'       # Nombre de tu Azure Function App en Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'    # Ruta donde está tu código de la Function
  NODE_VERSION: '22.x'                    # Versión de Node.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Descargar el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: npm install

      # 4️⃣ Ejecutar tests (opcional)
      - name: Run tests
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: npm test || echo "No tests found"

      # 5️⃣ Desplegar la Azure Function con Publish Profile
      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
